---
- hosts: mgmt
  become: yes
  roles:
    - mgmt
  handlers:
    - include: handlers/main.yml
      static: yes

- hosts: spines
  become: yes
  roles:
    - monitoring_agent
  handlers:
    - include: handlers/main.yml
      static: yes

- hosts: leafs
  become: yes
  roles:
    - monitoring_agent
  handlers:
    - include: handlers/main.yml
      static: yes
