---
- name: Copy /etc/network/interfaces
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
  notify: reload networking

- name: Copy Quagga Configuration
  template:
    src: Quagga.conf.j2
    dest: /etc/quagga/Quagga.conf
  notify: reload quagga

- name: Copy fping script
  template:
    src: fping_influxdb.py.j2
    dest: /usr/local/bin/fping-influxdb.py
    mode: 0755

- name: Copy telegraf configuration
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify: restart telegraf
